package com.simplemobiletools.calculator.helpers

val DIGIT = "digit"
val EQUALS = "equals"
val PLUS = "plus"
val MINUS = "minus"
val MULTIPLY = "multiply"
val DIVIDE = "divide"
val MODULO = "modulo"
val POWER = "power"
val ROOT = "root"
val DECIMAL = "decimal"
val CLEAR = "clear"
val RESET = "reset"
val LEFTBRACKET = "leftBracket"
val RIGHTBRACKET = "rightBracket"

val NAN = "NaN"
val ZERO = "zero"
val ONE = "one"
val TWO = "two"
val THREE = "three"
val FOUR = "four"
val FIVE = "five"
val SIX = "six"
val SEVEN = "seven"
val EIGHT = "eight"
val NINE = "nine"

// shared preferences
val VIBRATE_ON_BUTTON_PRESS = "vibrate_on_button_press"
