package com.simplemobiletools.calculator.helpers

val DIGIT = "digit"
val EQUALS = "equals"
val PLUS = "plus"
val MINUS = "minus"
val MULTIPLY = "multiply"
val DIVIDE = "divide"
val MODULO = "modulo"
val POWER = "power"
val ROOT = "root"
val DECIMAL = "decimal"
val CLEAR = "clear"
val RESET = "reset"

val ZERO = "zero"
val ONE = "one"
val TWO = "two"
val THREE = "three"
val FOUR = "four"
val FIVE = "five"
val SIX = "six"
val SEVEN = "seven"
val EIGHT = "eight"
val NINE = "nine"
