package com.simplemobiletools.calculator

val DIGIT = "digit"
val EQUALS = "equals"
val PLUS = "plus"
val MINUS = "minus"
val MULTIPLY = "multiply"
val DIVIDE = "divide"
val MODULO = "modulo"
val POWER = "power"
val ROOT = "root"
val DECIMAL = "decimal"
val CLEAR = "clear"
val RESET = "reset"

val ZERO = "zero"
val ONE = "one"
val TWO = "two"
val THREE = "three"
val FOUR = "four"
val FIVE = "five"
val SIX = "six"
val SEVEN = "seven"
val EIGHT = "eight"
val NINE = "nine"

// shared preferences
val PREFS_KEY = "Calculator"
val IS_FIRST_RUN = "is_first_run"
val IS_DARK_THEME = "is_dark_theme"
val WIDGET_BG_COLOR = "widget_bg_color"
val WIDGET_TEXT_COLOR = "widget_text_color"
